package eci.edu.dosw.parcial.TEEN_TITANS_BACK.model;

public enum requestType {
    REQUEST_FOR_GROUP_CHANGE,
    REQUEST_FOR_COURSE_CANCELATION,
    REQUEST_FOR_LATE_REGISTRATION,
    REQUEST_FOR_STUDENT_GROUP_EXCHANGE,
    COMPOSITE_REQUEST,
    REQUEST_FOR_EXCEPTIONAL_CIRCUMSTANCES
}